-- Marketing content media: images & videos attached to a content post, stored in
-- Supabase Storage. Uploaded by the team, or generated by Alfred (Nano Banana).
-- Run once in Supabase → SQL Editor.

-- 1. Storage bucket (public read so the studio + previews can show media by URL).
insert into storage.buckets (id, name, public)
values ('marketing-media', 'marketing-media', true)
on conflict (id) do nothing;

-- Anyone can read the files; signed-in users can upload / change / remove them.
drop policy if exists "marketing media read" on storage.objects;
create policy "marketing media read"
  on storage.objects for select
  using (bucket_id = 'marketing-media');

drop policy if exists "marketing media insert" on storage.objects;
create policy "marketing media insert"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'marketing-media');

drop policy if exists "marketing media update" on storage.objects;
create policy "marketing media update"
  on storage.objects for update to authenticated
  using (bucket_id = 'marketing-media');

drop policy if exists "marketing media delete" on storage.objects;
create policy "marketing media delete"
  on storage.objects for delete to authenticated
  using (bucket_id = 'marketing-media');

-- 2. Media rows, linked to a post (cascade-deleted with the post).
create table if not exists public.content_media (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.content_posts (id) on delete cascade,
  created_by uuid not null default auth.uid() references auth.users (id) on delete cascade,
  kind text not null default 'image',        -- image | video
  source text not null default 'upload',     -- upload | ai
  url text not null,                         -- public URL
  storage_path text not null,                -- path inside the bucket (for deletion)
  prompt text,                               -- set when AI-generated
  created_at timestamptz not null default now()
);

create index if not exists content_media_post_idx on public.content_media (post_id);

alter table public.content_media enable row level security;

drop policy if exists "content_media read" on public.content_media;
create policy "content_media read" on public.content_media
  for select to authenticated using (true);

drop policy if exists "content_media insert" on public.content_media;
create policy "content_media insert" on public.content_media
  for insert to authenticated with check (created_by = auth.uid());

drop policy if exists "content_media delete" on public.content_media;
create policy "content_media delete" on public.content_media
  for delete to authenticated using (true);
