/* Media attached to a content post — images & videos in Supabase Storage,
   uploaded by the team or generated by Alfred. Type only (importable by client
   components); the server actions live in `media-actions.ts`. */

export type ContentMedia = {
  id: string;
  post_id: string;
  created_by: string;
  kind: "image" | "video";
  source: "upload" | "ai";
  url: string;
  storage_path: string;
  prompt: string | null;
  created_at: string;
};

export const MEDIA_BUCKET = "marketing-media";
